-- Woyqe database schema (Supabase / PostgreSQL)
-- Run this in the Supabase SQL editor before starting the backend.
--
-- The backend talks to Supabase with the SERVICE ROLE key, which bypasses RLS.
-- RLS policies below are permissive placeholders; tighten them if you ever
-- expose these tables to the anon/browser key beyond Realtime.

create extension if not exists "pgcrypto";

-- ── Users ────────────────────────────────────────────────────────────────
create table if not exists public.users (
    id                uuid primary key default gen_random_uuid(),
    telegram_user_id  bigint unique not null,
    created_at        timestamptz not null default now()
);

-- ── Accounts (a connected messenger account) ─────────────────────────────
create table if not exists public.accounts (
    id                      uuid primary key default gen_random_uuid(),
    user_id                 uuid not null references public.users(id) on delete cascade,
    platform                text not null check (platform in ('instagram', 'max', 'vk')),
    external_user_id        text,
    username                text,
    display_name            text,
    avatar_url              text,
    status                  text not null default 'connected'
                              check (status in ('connecting', 'connected', 'error', 'disconnected')),
    session_data_encrypted  text,          -- Fernet-encrypted session; never leaves the backend
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now(),
    unique (user_id, platform, external_user_id)
);
create index if not exists accounts_user_platform_idx on public.accounts (user_id, platform);

-- ── Pending connections (2FA / challenge / QR / OAuth in progress) ────────
create table if not exists public.account_connections (
    id          uuid primary key,          -- id is generated by the connector
    user_id     uuid not null references public.users(id) on delete cascade,
    platform    text not null,
    method      text,                       -- credentials | qr | oauth
    status      text not null,              -- 2fa_required | challenge_required | waiting_for_scan | ...
    qr_data     text,
    created_at  timestamptz not null default now()
);

-- ── Chats / conversations ─────────────────────────────────────────────────
create table if not exists public.chats (
    id                 uuid primary key default gen_random_uuid(),
    account_id         uuid not null references public.accounts(id) on delete cascade,
    platform           text not null,
    external_chat_id   text not null,
    title              text,
    avatar_url         text,
    last_message_text  text,
    last_message_at    timestamptz,
    unread_count       integer not null default 0,
    created_at         timestamptz not null default now(),
    unique (account_id, external_chat_id)
);
create index if not exists chats_account_idx on public.chats (account_id);

-- ── Messages ──────────────────────────────────────────────────────────────
create table if not exists public.messages (
    id                   uuid primary key default gen_random_uuid(),
    chat_id              uuid not null references public.chats(id) on delete cascade,
    platform             text not null,
    external_message_id  text,
    sender_id            text,
    sender_name          text,
    text                 text,
    direction            text not null check (direction in ('incoming', 'outgoing')),
    status               text not null default 'delivered'
                           check (status in ('sending', 'sent', 'delivered', 'failed')),
    created_at           timestamptz not null default now(),
    unique (chat_id, external_message_id)
);
create index if not exists messages_chat_idx on public.messages (chat_id, created_at);

-- ── Realtime ──────────────────────────────────────────────────────────────
-- The frontend subscribes to INSERTs on `messages` (and `chats`) via Supabase
-- Realtime, so new incoming messages appear without a manual refresh.
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.chats;

-- ── RLS ─────────────────────────────────────────────────────────────────────
alter table public.users enable row level security;
alter table public.accounts enable row level security;
alter table public.account_connections enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;

-- Service role bypasses RLS automatically. Allow the anon key to READ messages
-- and chats so browser Realtime works; everything else stays backend-only.
drop policy if exists "anon can read messages" on public.messages;
create policy "anon can read messages" on public.messages for select using (true);

drop policy if exists "anon can read chats" on public.chats;
create policy "anon can read chats" on public.chats for select using (true);
